server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/tell_about
    username: root
    password: Ktgjxrf26102001$
    hikari:
      minimum-idle=2
      maximum-pool-size=10
      connection-timeout=30000
      idle-timeout=600000
      max-lifetime=1800000
  jpa:
    hibernate:
      ddl-auto: update